# Site settings
title: Hi. I'm Xiaoyao
navtitle: XIAOYAO YANG
header-img: img/new-york.jpg
email: robinxiaoyaoyang@gmail.com
copyright_name: Xiaoyao Yang
description: "In God we trust, all others bring data."
baseurl: ""
url: "http://xiaoyaoyang.github.io"
twitter_username:
github_username:  xiaoyaoyang
facebook_username:  xiaoyaoyoung
email_username:  robinxiaoyaoyang@gmail.com
linkedin_username: xiaoyaoyang


# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
